Code/SitecoreMVC/SitecoreMVC.Web/Controllers/PageController.cs
using SitecoreMVC.Business.Metadata;
using SitecoreMVC.Business.Scripts;
using System.Web.Mvc;

namespace SitecoreMVC.Web.Controllers
{
    public class PageController : Controller
    {
        private readonly IMetadataLogic _metadataLogic;
        private readonly IScriptsLogic _scriptsLogic;
        private readonly ICanonicalLink _canonicalLink;

        public PageController(IMetadataLogic metadataLogic, IScriptsLogic scriptsLogic, ICanonicalLink canonicalLink)
        {
            _metadataLogic = metadataLogic;
            _scriptsLogic = scriptsLogic;
            _canonicalLink = canonicalLink;
        }

        public ActionResult GetMetadata()
        {
            return Content(_metadataLogic.GetMetatags());
        }

        public ActionResult GetHeaderScripts()
        {
            return Content(_scriptsLogic.GetHeaderScripts());
        }

        public ActionResult GetStartBodyScripts()
        {
            return Content(_scriptsLogic.GetStartBodyScripts());
        }

        public ActionResult GetEndBodyScripts()
        {
            return Content(_scriptsLogic.GetEndBodyScripts());
        }

        public ActionResult GetCanonicalLink()
        {
            return Content(_canonicalLink.GetCanonicalLink());
        }
    }
}

Code/SitecoreMVC/SitecoreMVC.Web/Views/Layouts/Main.cshtml
@using Sitecore.Mvc
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">

    <!-- bundles for css -->
    <!-- bundles for scripts -->

    @Html.Action("GetMetadata", "Page")
    @Html.Action("GetHeaderScripts", "Page")
    @Html.Action("GetCanonicalLink", "Page")
</head>
<body>
    @Html.Action("GetStartBodyScripts", "Page")
    <header>
        @Html.Sitecore().Placeholder("phHeader")
    </header>
    @Html.Sitecore().Placeholder("phContent")
    <footer>
        @Html.Sitecore().Placeholder("phFooter")
    </footer>
    @Html.Action("GetEndBodyScripts", "Page")
</body>
</html>